# Generated by Django 5.0.4 on 2024-08-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_userprofile_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('cropped_image', models.ImageField(blank=True, null=True, upload_to='cropped_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
